name: 'Docker Image CI'
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    options: --user root

    steps:

    - name: clone repo
      uses: actions/checkout@v2
      with:
        repository: go-skynet/LocalAI-frontend

    - name: copy files
      run: mv /home/runner/work/localai-frontend/localai-frontend /

    - name: ls dir
      run: ls -la
      working-directory: /localai-frontend

    # - name: setup node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.x'

    # - name: npm install
    #   run: npm install
    #   working-directory: /home/runner/work/localai-frontend/localai-frontend